name:                log-store-examples
version:             0.1.0.0
github:              "daleiz/log-store-examples"
license:             BSD3
author:              "Wangbin"
maintainer:          "wangbin@emqx.com"
copyright:           "2020 Wangbin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/log-store-test#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- rocksdb-haskell
- log-store
- conduit

executables:
  log-store-examples-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []

tests:
  log-store-examples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []
